### ISSUE TITLE
Error when trying to mount

### ISSUE THREAD

**Issue by eldada** [ulrichSchreiner/nfs-server#1]
When I try a simple mount from another Linux container
```
mount nfsserver:/data /mnt/
or
mount -t nfs nfsserver:/data /mnt/
```
I get an error
```
mount: permission denied
```

Any special permissions I need to use?

**Comment by ulrichSchreiner** [comment]
to mount a nfs share you need special rights, therefore you have to start your container (which does the mount) with `--privileged`.

Or you mount your share outside of the container and use `-v` to mount the host-nfs-share into a conatiner.
